### ISSUE TITLE
English format of the date

### ISSUE THREAD

**Issue by karimalisaber** [EslamElmadny/HijriGregorianDatepicker#20]
could I use date English format for example (Saturday instead of السبت, January instead of يناير  ) and so on

**Comment by EslamElmadny** [comment]
Hello,

Unfortunately at the time being no. Please refer to [projects/ngx-hijri-gregorian-datepicker/src/lib/hijri-gregorian-datepicker/IslamicI18n.ts.](https://github.com/EslamElmadny/HijriGregorianDatepicker/blob/master/projects/ngx-hijri-gregorian-datepicker/src/lib/hijri-gregorian-datepicker/IslamicI18n.ts)
 But we can consider it in the near future.
