### ISSUE TITLE
placeholder editing

### ISSUE THREAD

**Issue by ahmedfares19** [EslamElmadny/HijriGregorianDatepicker#6]
I think placeholder should be editable and reachable with a default value 
![image](https://user-images.githubusercontent.com/29165467/104611397-bad79480-568d-11eb-9a66-c513d85be201.png)

**Comment by EslamElmadny** [comment]
You can already provide a placeholder like this ..

https://github.com/EslamElmadny/HijriGregorianDatepicker/blob/5cee02696175d0f56baa650b8395a23b4fafb8f6/src/app/app.component.html#L15


and regarding your error ,, just wrap place holder with single quotes inside the double ones.
